# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: DotNetCoreCLI@2
  displayName: "Pack"
  inputs:
    command: 'pack'
    packagesToPack: '**/*.csproj'
    includesymbols: true
    versioningScheme: 'off'

- task: DownloadSecureFile@1
  name: "GetCertificate"
  inputs:
    secureFile: 'kchopein.pfx'

- task: PowerShell@2
  name: Sign
  inputs:
    targetType: 'inline'
    script: 'nuget sign $(Build.ArtifactStagingDirectory)/**/*.nupkg -CertificatePath $(GetCertificate.secureFilePath)'

- task: NuGetCommand@2
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'NuGet.org'
